spring:
  profiles:
    active:
    - dev
---
server:
  port: 9988
spring:
  profiles: dev  #开发环境
  application:
      name: microservicecloud-config-dept-client
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/clouddb01
      username: root
      password: root
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 20
        max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.dxh.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-9988    #更改client在server的标识符
    prefer-ip-address: true               #显示client的ip地址
info:
  app.name: microservicecloud-dept
  company.name: sylar
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 9988
spring:
  profiles: test  #开发环境
  application:
      name: microservicecloud-config-dept-client
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/clouddb01
      username: root
      password: root
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 20
        max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.dxh.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-9988    #更改client在server的标识符
    prefer-ip-address: true               #显示client的ip地址
info:
  app.name: microservicecloud-dept
  company.name: sylar
  build.artifactId: $project.artifactId$
  build.version: $project.version$